### PR TITLE
Adds Crystal's video link.

### PR DESCRIPTION
**Pull request by eliseworthy**
@sudocrystal @jnf @kariabancroft Do we have a PR process for changes to curriculum? Should we? Anyway, here's a small PR. :)

### CODE REVIEW

**Comment by kariabancroft** [comment]
We definitely do not have a PR process right now. As of right now we are changing a lot of files. If Jeremy and I review each other's changes it might not bog us down too much.

**Comment by eliseworthy** [comment]
@kariabancroft I'll follow your lead on what y'all want to do re: process. Once this intensive collaboration pre-class is over, having PRs would be a cool way to see what's changing and being added as we go.

**Comment by sudocrystal** [comment]
Yeah, I'm newer to github, so I still don't understand the process that needs to be followed. But if someone just tells me (explains to me) what to do, I'm happy to follow a process!

**Comment by jnf** [comment]
The "How to PR: A Rational and Super Fun Process" is probably my second most favorite lecture to give. The first is "Characteristics of a Good Whisk(e)y." Let me know if yinz are up for either. :)

**Comment by sudocrystal** [comment]
Yes, I’m definitely in on a PR talk from Jeremy! 

-- 
Crystal Hess
Program Manager, Ada Developers Academy
http://adadevelopersacademy.org/ | @adaacademy | 425.298.7549 (cell)

**Pull request merged**
