### PR TITLE
Fleshing out Code Quality

### PR DESCRIPTION
**Pull request by sudocrystal**
This isn’t complete yet, but so you can see what I’m doing…

### CODE REVIEW

**Comment by kariabancroft** [comment]
Should we include specific functionality in the "correctness" sections? i.e. "The add functionality works as expected using the name "add" and symbol "+". Or assume that all of that info is in the project definition

**Comment by sudocrystal** [comment]
Hmm... I imagined the bottom section would be standard to all programs (more or less), so I thought that might go in the first section (learning goals), but..... open to doing it differently. :)

**Comment by sudocrystal** [comment]
Sorry, that's all I have time for right now. You'll have to modify, fix, as necessary! Time for me to teach!

**Comment by sudocrystal** [comment]
Really quick answering Kari's question. -- I'd remove the things that aren't relevant !

**Pull request merged**
