### PR TITLE
Rough beginning for FarMar rubric

### PR DESCRIPTION
**Pull request by lkdamer**
Here's a rough start to the FarMar rubric. I'm not sure what sort of guidance to give on testing and a few other areas.

### CODE REVIEW

**Comment by kariabancroft** [comment]
Looks good! I do think we need more specific examples for module usage, gem usage & testing (mentioning edge case coverage, etc.) 

I think for gems we can just say something like "Gems are chosen and used for a specific purpose within the project". We may be able to flesh out the module usage verbiage a bit more once we figure out exactly how we'll be presenting it.

**Comment by sudocrystal** [comment]
Where it says "Level-Specific Requirements" --> new verbiage for bronze...platinum is breakfast/lunch/dinner/dessert. So those words need to be changed. Not trying to be too nit-picky, but I also feel like avoiding the word "level" is best. Maybe use "feature set" or "depth" or similar...?

**Comment by jnf** [comment]
I've been saying "project tiers," but I don't know if that's any better.

**Comment by jnf** [comment]
Imma merge this because I think it's great.

**Pull request merged**
