### PR TITLE
Tweak the layout of the rubric to make the examples easier to read.

### PR DESCRIPTION
**Pull request by jnf**
Not sure if this is better; what do yinz think?

### CODE REVIEW

**Comment by sudocrystal** [comment]
I actually like the examples in-line, personally.

**Comment by kariabancroft** [comment]
looks much better - the examples in line were confusing and using semi-colons andare just hard to read

**Comment by sudocrystal** [comment]
Actually, I agree on the if-statements about not in-line. So I suppose if some is not in-line, it's better that none are inline. If you merge this request, I'll try a change really quick on the bottom section.

**Comment by lkdamer** [comment]
I agree about the semi-colons making multi-line examples hard to read. Also, thanks for fixing my python syntax! I hadn't even noticed...

**Pull request merged**
